### ISSUE TITLE
Where is the un-minifed code?

### ISSUE THREAD

**Issue by arjunu** [tofuness/eex#2]
Sorry I couldn't find the un-minifed code for the experiments.

**Comment by tofuness** [comment]
Hi,

Open up any `index.html` file and scroll down to the bottom for the JS code.
Example: [https://github.com/tofuness/eex/blob/master/springy/index.html#L149](https://github.com/tofuness/eex/blob/master/springy/index.html#L149)

The minified files are just libraries.

**Comment by arjunu** [comment]
Thanks!
