### ISSUE TITLE
Satoshi visualizer doesn't work in Chrome on Android

### ISSUE THREAD

**Issue by ghost** [tofuness/eex#4]
It plays music, but shows just white ellipse without any animations.

**Comment by a-rodin** [comment]
It plays music, but shows just white ellipse without any animations.

**Comment by tofuness** [comment]
`getByteTimeDomainData()` doesn't work on mobile for some reason. The waveform data that gets put into the `Uint8Array` isn't correct. If anyone knows what I am doing wrong, please let me know.

**Comment by tofuness** [comment]
Wohoo! Now works in  Chrome on Android (super laggy).
